"use client";

import {
  AssistantRuntimeProvider, ComposerPrimitive, MessagePrimitive, ThreadPrimitive,
  useExternalStoreRuntime, type AppendMessage, type ThreadMessageLike,
} from "@assistant-ui/react";
import {
  Activity, ArrowUp, BookOpen, Brain, CalendarDays, Check, CheckCircle2, ChevronRight,
  Circle, Cloud, Database, Dumbbell, FolderKanban, Gauge, HeartPulse, Home, Link2,
  ListChecks, LockKeyhole, Menu, MessageCircle, MoreHorizontal, Pencil, Plus, RefreshCw,
  Search, Settings, ShieldCheck, Sparkles, Trash2, Webhook, X,
} from "lucide-react";
import { FormEvent, useCallback, useEffect, useMemo, useState, type ReactNode } from "react";

type View = "home"|"chat"|"today"|"calendar"|"projects"|"study"|"workouts"|"memory"|"integrations"|"settings";
type CoreState = "idle"|"retrieving"|"searching"|"calendar"|"routing"|"thinking"|"speaking"|"error";
type Source = { title:string; url:string; snippet?:string };
type ChatMessage = { id:string; role:"user"|"assistant"; text:string; model?:string; sources?:Source[] };
type DailyItem = { id:number; title:string; kind:string; source_type:string; source_id?:string|null; status:"todo"|"doing"|"done"|"skipped"; scheduled_at?:number|null; duration_minutes?:number; priority?:number; notes?:string };
type Memory = { id:number; category:string; content:string; importance:number; privacy?:"public"|"personal"|"sensitive"|"restricted"; confidence?:number; source?:string; locked?:number; updated_at?:number };
type Project = { id:number; name:string; description?:string; status:string; priority:number; due_at?:number|null; done_tasks:number; task_count:number; open_tasks:number; tasks?:Array<{id:number;title:string;status:string;due_at?:number|null}> };
type GraphNode = { id:number; label:string; node_type:string; privacy:string; importance:number; memory_id?:number|null };
type GraphEdge = { id:number; source:number; target:number; relation:string; weight:number };
type SilkData = {
  history:Array<{id:number;role:"user"|"assistant";content:string;sources?:Source[]}>; memories:Memory[]; projects:Project[];
  today:{date:string;items:DailyItem[];progress:{completed:number;total:number;percent:number};week:{completed:number;total:number};focus_minutes:number;deadlines:Array<{id:number;name:string;due_at:number;priority:number}>;synced_at:number};
  study:{sessions?:Array<Record<string,unknown>>;latest?:Record<string,unknown>;weakest_topics?:Array<Record<string,unknown>>};
  workouts:{active?:Record<string,unknown>|null;recent?:Array<Record<string,unknown>>;history?:Array<Record<string,unknown>>};
  usage:Record<string,unknown>&{requests?:number;paid_cost_cad?:number;openai_spend_limit_usd?:number;openai_remaining_usd?:number;providers?:Record<string,Record<string,number>>};
  google:{configured:boolean;connected:boolean;account_email?:string}; web:{configured?:boolean;provider?:string};
  ai:{primary_provider?:string;router_model?:string;routine_model?:string;complex_model?:string;spent_this_month_usd?:number;spend_limit_usd?:number;remaining_usd?:number;circuit_open?:boolean};
  settings:{owner_name:string;assistant_name:string;model_mode:string;response_length:string;monthly_budget_cad:string};
};

const dateKey=()=>new Date(Date.now()-new Date().getTimezoneOffset()*60000).toISOString().slice(0,10);
const now=()=>Math.floor(Date.now()/1000);
const previewData:SilkData={
  history:[{id:1,role:"assistant",content:"Silk OS is online. This preview uses sample data until your Cloudflare secrets and private D1 database are attached."}],
  memories:[
    {id:1,category:"assistant",content:"Lead with evidence, then give the recommendation.",importance:5,privacy:"personal",confidence:1,source:"manual"},
    {id:2,category:"school",content:"Pre-Health study results should be reviewed by topic.",importance:4,privacy:"personal",confidence:.95,source:"conversation"},
    {id:3,category:"fitness",content:"Track weights, reps, RPE, warmups, and personal records.",importance:4,privacy:"sensitive",confidence:.9,source:"conversation"},
  ],
  projects:[
    {id:1,name:"Build Silk",description:"Turn Silk into a real assistant OS.",status:"active",priority:5,done_tasks:8,task_count:12,open_tasks:4,tasks:[{id:1,title:"Connect Google Calendar",status:"doing"},{id:2,title:"Finish memory controls",status:"todo"}]},
    {id:2,name:"Pre-Health Review",description:"Organize study gaps and comeback exams.",status:"active",priority:4,done_tasks:3,task_count:6,open_tasks:3,tasks:[]},
  ],
  today:{date:dateKey(),items:[
    {id:1,title:"Anatomical planes review",kind:"task",source_type:"study",status:"todo",duration_minutes:45,priority:5},
    {id:2,title:"Build Silk v0.6",kind:"task",source_type:"project",status:"doing",duration_minutes:90,priority:5},
    {id:3,title:"Incline chest press",kind:"task",source_type:"workout",status:"done",duration_minutes:25,priority:3},
  ],progress:{completed:1,total:3,percent:33},week:{completed:9,total:14},focus_minutes:270,deadlines:[{id:1,name:"Silk v0.6 deployment",due_at:now()+259200,priority:5}],synced_at:now()},
  study:{sessions:[],weakest_topics:[{topic:"Anatomical planes",score:40}]},workouts:{active:null,recent:[]},
  usage:{requests:23,paid_cost_cad:.08,openai_spend_limit_usd:10,openai_remaining_usd:9.94,providers:{openai:{requests:8},cloudflare:{requests:15}}},
  google:{configured:false,connected:false},web:{configured:false,provider:"Tavily"},
  ai:{primary_provider:"openai",router_model:"gpt-5-nano",routine_model:"gpt-5.6-luna",complex_model:"gpt-5.6-terra",spent_this_month_usd:.06,spend_limit_usd:10,remaining_usd:9.94},
  settings:{owner_name:"Jaed",assistant_name:"Silk",model_mode:"automatic",response_length:"concise",monthly_budget_cad:"2"},
};

const NAV:Array<{id:View;label:string;icon:typeof Home}>=[
  {id:"home",label:"Overview",icon:Home},{id:"chat",label:"Ask Silk",icon:MessageCircle},{id:"today",label:"Today",icon:ListChecks},
  {id:"calendar",label:"Calendar",icon:CalendarDays},{id:"projects",label:"Projects",icon:FolderKanban},{id:"study",label:"Study",icon:BookOpen},
  {id:"workouts",label:"Workouts",icon:Dumbbell},{id:"memory",label:"Memory",icon:Brain},{id:"integrations",label:"Connections",icon:Link2},{id:"settings",label:"Settings",icon:Settings},
];

async function api<T=Record<string,unknown>>(path:string,options:RequestInit={}):Promise<T>{
  const response=await fetch(path,{credentials:"same-origin",...options,headers:{"Content-Type":"application/json",...(options.headers||{})}});
  const body=await response.json().catch(()=>({})) as Record<string,unknown>;
  if(!response.ok)throw new Error(typeof body.error==="string"?body.error:`Request failed (${response.status})`);return body as T;
}

export default function SilkOS(){
  const [session,setSession]=useState<{configured:boolean;authenticated:boolean;version:string}|null>(null);
  const [data,setData]=useState<SilkData>(previewData);const [view,setView]=useState<View>("home");const [preview,setPreview]=useState(false);
  const [loading,setLoading]=useState(true);const [menu,setMenu]=useState(false);const [notice,setNotice]=useState("");const [voice,setVoice]=useState(false);
  const [activity,setActivity]=useState<{state:CoreState;label:string}>({state:"idle",label:"Ready"});
  const load=useCallback(async()=>{try{setData(await api<SilkData>("/api/bootstrap"));setPreview(false);}catch(error){setNotice(error instanceof Error?error.message:"Silk could not load your data.");}},[]);
  useEffect(()=>{let active=true;(async()=>{try{const current=await api<{configured:boolean;authenticated:boolean;version:string}>("/api/session",{headers:{}});if(!active)return;setSession(current);if(!current.configured){setPreview(true);setData(previewData);}else if(current.authenticated)await load();}catch{if(active){setSession({configured:false,authenticated:false,version:"Silk OS v0.6"});setPreview(true);}}finally{if(active)setLoading(false);}})();return()=>{active=false};},[load]);
  const refresh=useCallback(async()=>{if(preview)return;setActivity({state:"retrieving",label:"Refreshing Silk"});await load();setActivity({state:"idle",label:"Ready"});},[load,preview]);
  if(loading)return <Boot/>;
  if(session?.configured&&!session.authenticated)return <Login onSuccess={async()=>{setSession({...session,authenticated:true});await load();}}/>;
  const title=NAV.find(item=>item.id===view)?.label||"Silk";
  return <main className="silk-shell">
    <aside className={`silk-sidebar ${menu?"open":""}`}><div className="brand-block"><Mark small/><div><strong>SILK</strong><span>Personal intelligence</span></div><button className="icon-button mobile-only" onClick={()=>setMenu(false)}><X size={18}/></button></div>
      <nav className="side-nav">{NAV.map(({id,label,icon:Icon})=><button key={id} className={view===id?"active":""} onClick={()=>{setView(id);setMenu(false)}}><Icon size={18}/><span>{label}</span>{view===id&&<i/>}</button>)}</nav>
      <div className="sidebar-foot"><div className="security-chip"><ShieldCheck size={15}/> Owner-only</div><span>{preview?"Preview data":"Cloudflare + private D1"}</span></div>
    </aside>
    <section className="silk-workspace"><header className="topbar"><div className="topbar-title"><button className="icon-button mobile-only" onClick={()=>setMenu(true)}><Menu size={20}/></button><div><span className="eyebrow">SILK OS / {title.toUpperCase()}</span><h1>{title}</h1></div></div><div className="top-actions">{preview&&<span className="preview-badge">PREVIEW</span>}<button className="quiet-button" onClick={()=>setVoice(!voice)}><Activity size={16}/> Voice {voice?"on":"off"}</button><button className="icon-button" onClick={refresh}><RefreshCw size={17}/></button></div></header>
      {notice&&<div className="notice"><span>{notice}</span><button onClick={()=>setNotice("")}><X size={16}/></button></div>}
      <div className="workspace-scroll">
        {view==="home"&&<Dashboard data={data} preview={preview} nav={setView} refresh={refresh}/>} {view==="chat"&&<Chat initial={data.history} preview={preview} voice={voice} setActivity={setActivity} refresh={refresh}/>} {view==="today"&&<Today data={data.today} preview={preview} refresh={refresh} notice={setNotice}/>} {view==="calendar"&&<Calendar data={data} preview={preview} refresh={refresh} notice={setNotice}/>} {view==="projects"&&<Projects data={data.projects} preview={preview} refresh={refresh} notice={setNotice}/>} {view==="study"&&<Study data={data.study}/>} {view==="workouts"&&<Workouts data={data.workouts}/>} {view==="memory"&&<MemoryView data={data.memories} preview={preview} refresh={refresh} notice={setNotice}/>} {view==="integrations"&&<Integrations data={data} preview={preview}/>} {view==="settings"&&<SettingsView data={data} preview={preview} refresh={refresh} notice={setNotice}/>} 
      </div>
    </section>
    <aside className="core-rail"><Core activity={activity} data={data}/></aside>
    <nav className="mobile-tabs">{NAV.filter(item=>["home","chat","today","memory"].includes(item.id)).map(({id,label,icon:Icon})=><button key={id} className={view===id?"active":""} onClick={()=>setView(id)}><Icon size={19}/><span>{label}</span></button>)}<button onClick={()=>setMenu(true)}><MoreHorizontal size={19}/><span>More</span></button></nav>
  </main>;
}

function Mark({small=false}:{small?:boolean}){return <div className={`silk-mark ${small?"small":""}`} aria-hidden><span/><span/><span/></div>}
function Boot(){return <main className="boot-screen"><Mark/><div><strong>SILK OS</strong><span>Initializing private workspace</span></div></main>}
function Login({onSuccess}:{onSuccess:()=>Promise<void>}){const [password,setPassword]=useState("");const [error,setError]=useState("");const [busy,setBusy]=useState(false);const submit=async(e:FormEvent)=>{e.preventDefault();setBusy(true);setError("");try{await api("/api/login",{method:"POST",body:JSON.stringify({password})});await onSuccess()}catch(reason){setError(reason instanceof Error?reason.message:"Sign-in failed.")}finally{setBusy(false)}};return <main className="login-screen"><div className="login-panel"><Mark/><span className="eyebrow">PRIVATE PERSONAL OS</span><h1>Unlock Silk</h1><p>Your data stays behind your owner passphrase and same-origin session.</p><form onSubmit={submit}><label htmlFor="pass">Owner passphrase</label><input id="pass" type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} autoFocus/>{error&&<div className="field-error">{error}</div>}<button className="primary-button" disabled={busy||!password}>{busy?"Unlocking…":"Unlock workspace"}<ChevronRight size={17}/></button></form></div></main>}
function Panel({title,eyebrow,action,className="",children}:{title:string;eyebrow?:string;action?:ReactNode;className?:string;children:ReactNode}){return <section className={`panel ${className}`}><header className="panel-head"><div>{eyebrow&&<span className="eyebrow">{eyebrow}</span>}<h2>{title}</h2></div>{action}</header>{children}</section>}
function Metric({label,value,detail,progress}:{label:string;value:string;detail:string;progress?:number}){return <article className="metric-card"><span>{label}</span><strong>{value}</strong><small>{detail}</small>{progress!==undefined&&<div className="progress"><i style={{width:`${Math.min(100,Math.max(0,progress))}%`}}/></div>}</article>}
function Timeline({item,toggle}:{item:DailyItem;toggle?:(item:DailyItem)=>void}){return <article className={`timeline-item ${item.status}`}><button className="task-check" onClick={()=>toggle?.(item)}>{item.status==="done"?<Check size={14}/>:<Circle size={14}/>}</button><div><strong>{item.title}</strong><span>{item.source_type} · {minutes(Number(item.duration_minutes||0))}{item.scheduled_at?` · ${clock(item.scheduled_at)}`:""}</span></div><em>P{item.priority||3}</em></article>}
function Empty({icon:Icon,title,detail}:{icon:typeof Home;title:string;detail:string}){return <div className="empty-state"><Icon size={21}/><div><strong>{title}</strong><span>{detail}</span></div></div>}
function Signal({icon:Icon,label,value,muted=false}:{icon:typeof Home;label:string;value:string;muted?:boolean}){return <div className={`signal ${muted?"muted":""}`}><Icon size={18}/><span><small>{label}</small><strong>{value}</strong></span></div>}
function Rule({children}:{children:ReactNode}){return <div className="rule"><Check size={14}/><span>{children}</span></div>}

function Dashboard({data,preview,nav,refresh}:{data:SilkData;preview:boolean;nav:(v:View)=>void;refresh:()=>Promise<void>}){const todo=data.today.items.filter(i=>!["done","skipped"].includes(i.status)).slice(0,4);const deadline=data.today.deadlines[0];return <div className="page-grid"><section className="status-strip"><div><i/><span>{preview?"Preview workspace":"Systems operational"}</span></div><span>Synced {relative(data.today.synced_at)}</span></section><div className="metric-row"><Metric label="Completed today" value={`${data.today.progress.completed}/${data.today.progress.total}`} detail={`${data.today.progress.percent}% of tracked items`} progress={data.today.progress.percent}/><Metric label="This week" value={`${data.today.week.completed}/${data.today.week.total}`} detail="tasks completed" progress={data.today.week.total?data.today.week.completed/data.today.week.total*100:0}/><Metric label="Focus capacity" value={minutes(data.today.focus_minutes)} detail="after calendar blocks"/><Metric label="Paid AI this month" value={money(Number(data.usage.paid_cost_cad||0))} detail={`${Number(data.usage.requests||0)} total calls`}/></div>
  <Panel title="Today" eyebrow={data.today.date} className="span-2" action={<button className="text-button" onClick={()=>nav("today")}>Open tracker <ChevronRight size={15}/></button>}><div className="timeline-list">{todo.length?todo.map(item=><Timeline key={item.id} item={item}/>):<Empty icon={CheckCircle2} title="The queue is clear" detail="Add a task or sync Calendar."/>}</div></Panel>
  <Panel title="Priority signal" eyebrow="NEXT RECOMMENDATION"><div className="recommendation-card"><Sparkles size={20}/><p>{todo[0]?`${todo[0].title} is the highest-priority unfinished item. I recommend starting there.`:"No unfinished work is tracked. I recommend planning the next meaningful task first."}</p></div>{deadline&&<div className="deadline-line"><span>Nearest</span><strong>{deadline.name}</strong><small>{date(deadline.due_at)}</small></div>}</Panel>
  <Panel title="Active projects" eyebrow="SILK-ONLY TRACKER" className="span-2" action={<button className="text-button" onClick={()=>nav("projects")}>All projects <ChevronRight size={15}/></button>}><div className="project-mini-grid">{data.projects.filter(p=>p.status==="active").slice(0,3).map(p=><ProjectMini key={p.id} p={p}/>)}</div></Panel>
  <Panel title="Readiness" eyebrow="STUDY + TRAINING"><Signal icon={BookOpen} label="Study focus" value={String(data.study.weakest_topics?.[0]?.topic||"No gap recorded")}/><Signal icon={Dumbbell} label="Workout" value={data.workouts.active?"Session in progress":"No active session"}/><Signal icon={HeartPulse} label="Apple Health" value="Native companion required" muted/></Panel>
  <button className="sync-banner" onClick={refresh}><RefreshCw size={17}/><span><strong>Refresh the daily brief</strong><small>Calendar, projects, usage, study, and workouts</small></span><ChevronRight size={17}/></button></div>}
function ProjectMini({p}:{p:Project}){const percent=p.task_count?Math.round(p.done_tasks/p.task_count*100):0;return <article className="project-mini"><div><FolderKanban size={18}/><span>P{p.priority}</span></div><h3>{p.name}</h3><p>{p.description||`${p.open_tasks} tasks remain`}</p><div className="progress"><i style={{width:`${percent}%`}}/></div><small>{p.done_tasks}/{p.task_count} complete</small></article>}

function Chat({initial,preview,voice,setActivity,refresh}:{initial:SilkData["history"];preview:boolean;voice:boolean;setActivity:(v:{state:CoreState;label:string})=>void;refresh:()=>Promise<void>}){
  const [messages,setMessages]=useState<ChatMessage[]>(()=>initial.map(m=>({id:String(m.id),role:m.role,text:m.content,sources:m.sources})));const [running,setRunning]=useState(false);
  const send=useCallback(async(text:string)=>{setMessages(current=>[...current,{id:crypto.randomUUID(),role:"user",text}]);if(preview){setActivity({state:"routing",label:"Previewing model selection"});setTimeout(()=>{setMessages(current=>[...current,{id:crypto.randomUUID(),role:"assistant",text:"This is the interface preview. After deployment, this composer streams factual tool activity and routes work through Nano, Luna, or Terra.",model:"Preview"}]);setActivity({state:"idle",label:"Ready"})},450);return}setRunning(true);try{const response=await fetch("/api/chat/stream",{method:"POST",credentials:"same-origin",headers:{"Content-Type":"application/json"},body:JSON.stringify({message:text})});if(!response.ok||!response.body)throw new Error("Silk could not open the response stream.");const reader=response.body.getReader(),decoder=new TextDecoder();let buffer="";while(true){const {done,value}=await reader.read();if(done)break;buffer+=decoder.decode(value,{stream:true});const frames=buffer.split("\n\n");buffer=frames.pop()||"";for(const frame of frames){const event=frame.split("\n").find(line=>line.startsWith("event:"))?.slice(6).trim();const raw=frame.split("\n").find(line=>line.startsWith("data:"))?.slice(5).trim();if(!event||!raw)continue;const payload=JSON.parse(raw);if(event==="activity")setActivity(payload);if(event==="message"){setMessages(current=>[...current,{id:crypto.randomUUID(),role:"assistant",text:payload.reply,model:payload.model,sources:payload.sources||[]}]);if(voice&&"speechSynthesis"in window){setActivity({state:"speaking",label:"Speaking"});const speech=new SpeechSynthesisUtterance(payload.reply);speech.rate=1.03;speech.onend=()=>setActivity({state:"idle",label:"Ready"});window.speechSynthesis.speak(speech)}}if(event==="error")throw new Error(payload.error||"Silk could not answer.")}}await refresh()}catch(error){setMessages(current=>[...current,{id:crypto.randomUUID(),role:"assistant",text:error instanceof Error?error.message:"Silk could not answer.",model:"Error"}]);setActivity({state:"error",label:"Connection error"})}finally{setRunning(false)}},[preview,refresh,setActivity,voice]);
  const runtime=useExternalStoreRuntime({messages,isRunning:running,convertMessage:(m:ChatMessage):ThreadMessageLike=>({id:m.id,role:m.role,content:[{type:"text",text:m.text}]}),onNew:async(m:AppendMessage)=>{const text=m.content.filter(p=>p.type==="text").map(p=>p.text).join("\n").trim();if(text)await send(text)}});
  return <AssistantRuntimeProvider runtime={runtime}><ThreadPrimitive.Root className="chat-thread"><ThreadPrimitive.Viewport className="chat-viewport"><div className="chat-intro"><Mark small/><div><span className="eyebrow">DIRECT CHANNEL</span><h2>Ask Silk</h2><p>Conversation, tools, and private context in one workspace.</p></div></div><ThreadPrimitive.Messages>{({message})=><MessagePrimitive.Root className={`chat-message ${message.role}`}><div className="message-label">{message.role==="assistant"?"SILK":"YOU"}</div><div className="message-bubble"><MessagePrimitive.Parts/></div></MessagePrimitive.Root>}</ThreadPrimitive.Messages>{running&&<div className="typing-line"><i/><i/><i/> Silk is working</div>}<ThreadPrimitive.ViewportFooter className="composer-footer"><ComposerPrimitive.Root className="composer-root"><ComposerPrimitive.Input className="composer-input" placeholder="Ask Silk, update your day, or say good morning…" rows={1}/><ComposerPrimitive.Send className="composer-send"><ArrowUp size={18}/></ComposerPrimitive.Send></ComposerPrimitive.Root><small>Nano routes · Luna handles routine work · Terra handles complex work</small></ThreadPrimitive.ViewportFooter></ThreadPrimitive.Viewport></ThreadPrimitive.Root></AssistantRuntimeProvider>;
}

function Today({data,preview,refresh,notice}:{data:SilkData["today"];preview:boolean;refresh:()=>Promise<void>;notice:(s:string)=>void}){const [title,setTitle]=useState("");const toggle=async(item:DailyItem)=>{if(preview)return notice("Preview tasks do not change your private database.");try{await api(`/api/today/${item.id}`,{method:"PATCH",body:JSON.stringify({status:item.status==="done"?"todo":"done",completion_source:"dashboard"})});await refresh()}catch(e){notice(e instanceof Error?e.message:"Could not update the task.")}};const add=async(e:FormEvent)=>{e.preventDefault();if(!title.trim())return;if(preview)return notice("Deploy Silk to add real tasks.");try{await api("/api/today",{method:"POST",body:JSON.stringify({date:data.date,title,priority:3})});setTitle("");await refresh()}catch(err){notice(err instanceof Error?err.message:"Could not add the task.")}};return <div className="page-grid"><div className="metric-row"><Metric label="Today" value={`${data.progress.completed}/${data.progress.total}`} detail="items complete" progress={data.progress.percent}/><Metric label="Week" value={`${data.week.completed}/${data.week.total}`} detail="tracked completions"/><Metric label="Focus room" value={minutes(data.focus_minutes)} detail="estimated capacity"/></div><Panel title="Daily tracker" eyebrow={data.date} className="span-2" action={<button className="quiet-button" onClick={refresh}><RefreshCw size={15}/> Sync</button>}><form className="inline-add" onSubmit={add}><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Add a task to today"/><button><Plus size={18}/></button></form><div className="timeline-list expanded">{data.items.map(item=><Timeline key={item.id} item={item} toggle={toggle}/>)}</div></Panel><Panel title="Upcoming deadlines" eyebrow="NEXT 7 DAYS">{data.deadlines.length?data.deadlines.map(d=><div className="deadline-line" key={d.id}><span>P{d.priority}</span><strong>{d.name}</strong><small>{date(d.due_at)}</small></div>):<Empty icon={CheckCircle2} title="No nearby deadlines" detail="Project deadlines will appear here."/>}</Panel></div>}
function Calendar({data,preview,refresh,notice}:{data:SilkData;preview:boolean;refresh:()=>Promise<void>;notice:(s:string)=>void}){const events=data.today.items.filter(i=>i.source_type==="calendar");return <div className="page-grid"><Panel title="Google Calendar" eyebrow="SECURE OAUTH CONNECTION" className="span-2" action={data.google.connected?<span className="connected-chip"><Check size={14}/> Connected</span>:null}><div className="connection-hero"><div className="connection-icon"><CalendarDays/></div><div><h3>{data.google.connected?data.google.account_email||"Google Calendar connected":"Calendar is not connected"}</h3><p>{data.google.connected?"Events are copied into Today as linked items. Completing one never deletes the Google event.":"Google protects sign-in. Silk stores encrypted OAuth tokens; your Google password never enters Silk."}</p></div>{!data.google.connected&&<button className="primary-button" onClick={()=>preview?notice("Google OAuth is connected after Cloudflare deployment."):location.assign("/api/google/connect")}>Connect Google</button>}</div></Panel><Panel title="Today’s events" eyebrow="LIVE CALENDAR COPY" className="span-2">{events.length?<div className="timeline-list expanded">{events.map(item=><Timeline key={item.id} item={item}/>)}</div>:<Empty icon={CalendarDays} title="No events loaded" detail="Connect Calendar or refresh today."/>}</Panel><Panel title="Sync rules" eyebrow="SAFE BY DEFAULT"><Rule>Google remains the source of truth.</Rule><Rule>Silk creates linked Today items.</Rule><Rule>Completing an item does not edit Calendar.</Rule><button className="quiet-button full" onClick={refresh}><RefreshCw size={15}/> Refresh Calendar</button></Panel></div>}
function Projects({data,preview,refresh,notice}:{data:Project[];preview:boolean;refresh:()=>Promise<void>;notice:(s:string)=>void}){const [name,setName]=useState("");const add=async(e:FormEvent)=>{e.preventDefault();if(!name.trim())return;if(preview)return notice("Deploy Silk to save projects.");try{await api("/api/projects",{method:"POST",body:JSON.stringify({name,priority:3})});setName("");await refresh()}catch(err){notice(err instanceof Error?err.message:"Could not create the project.")}};return <div className="page-grid"><Panel title="Private project tracker" eyebrow="SILK-ONLY DATA" className="span-3"><form className="inline-add" onSubmit={add}><input value={name} onChange={e=>setName(e.target.value)} placeholder="Create a project"/><button><Plus size={18}/></button></form><div className="project-board">{data.map(p=><article className="project-card" key={p.id}><header><span>{p.status}</span><em>P{p.priority}</em></header><h3>{p.name}</h3><p>{p.description||"No description yet."}</p><div className="progress"><i style={{width:`${p.task_count?p.done_tasks/p.task_count*100:0}%`}}/></div><small>{p.done_tasks}/{p.task_count} tasks complete</small><div className="project-tasks">{p.tasks?.filter(t=>t.status!=="done").slice(0,3).map(t=><span key={t.id}><Circle size={11}/>{t.title}</span>)}</div></article>)}</div></Panel></div>}
function Study({data}:{data:SilkData["study"]}){return <div className="page-grid"><Panel title="Learning signal" eyebrow="PRE-HEALTH REVIEW" className="span-2"><div className="hero-stat"><BookOpen/><div><strong>{data.sessions?.length||0}</strong><span>saved study sessions</span></div></div><p className="panel-copy">Paste a graded study summary into Silk to structure the grade, strengths, weaknesses, topics, and next step. OneNote export follows Microsoft OAuth.</p></Panel><Panel title="Priority gap" eyebrow="EVIDENCE FIRST">{data.weakest_topics?.length?data.weakest_topics.slice(0,4).map((t,i)=><div className="score-row" key={i}><span>{String(t.topic||"Topic")}</span><strong>{t.score==null?"—":`${t.score}%`}</strong></div>):<Empty icon={BookOpen} title="No graded topics" detail="Save a study session to build this view."/>}</Panel><Panel title="OneNote pipeline" eyebrow="NEXT INTEGRATION" className="span-3"><div className="pipeline"><span>ChatGPT notes</span><ChevronRight/><span>Silk review</span><ChevronRight/><span>Structured record</span><ChevronRight/><span>OneNote</span></div></Panel></div>}
function Workouts({data}:{data:SilkData["workouts"]}){return <div className="page-grid"><Panel title="Workout control" eyebrow="LIVE SESSION" className="span-2">{data.active?<div className="hero-stat"><Dumbbell/><div><strong>{String(data.active.name||"Active workout")}</strong><span>session in progress</span></div></div>:<Empty icon={Dumbbell} title="No workout running" detail="Tell Silk you are starting a workout."/>}<div className="workout-command">“I finished incline chest press at 70 lbs for 8 reps, RPE 8.”</div></Panel><Panel title="Health signal" eyebrow="NATIVE APP REQUIRED"><Signal icon={HeartPulse} label="Apple Health" value="Not connected" muted/><p className="panel-copy">HealthKit cannot be read by a website. A future iPhone companion will sync only approved categories.</p></Panel><Panel title="What Silk tracks" eyebrow="D1 WORKOUT HISTORY" className="span-3"><div className="feature-pills">{["Exercises","Weights","Reps","RPE","Warmups","PR history"].map(x=><span key={x}>{x}</span>)}</div></Panel></div>}

function MemoryView({data,preview,refresh,notice}:{data:Memory[];preview:boolean;refresh:()=>Promise<void>;notice:(s:string)=>void}){const [mode,setMode]=useState<"library"|"map">("library");const [graph,setGraph]=useState<{nodes:GraphNode[];edges:GraphEdge[]}>({nodes:[],edges:[]});const [query,setQuery]=useState("");const [editing,setEditing]=useState<Memory|null>(null);const loadGraph=useCallback(async(search="")=>{if(preview)return setGraph(previewGraph(data,search));try{setGraph(await api(`/api/memory/graph?limit=52&query=${encodeURIComponent(search)}`))}catch(e){notice(e instanceof Error?e.message:"Could not load the memory map.")}},[data,notice,preview]);const remove=async(m:Memory)=>{if(!confirm(`Delete this memory?\n\n${m.content}`))return;if(preview)return notice("Preview memories cannot be deleted.");try{await api(`/api/memories/${m.id}`,{method:"DELETE"});await refresh()}catch(e){notice(e instanceof Error?e.message:"Could not delete memory.")}};const save=async(m:Memory)=>{if(preview){notice("Deploy Silk to edit real memories.");setEditing(null);return}try{await api(`/api/memories/${m.id}`,{method:"PATCH",body:JSON.stringify(m)});setEditing(null);await refresh()}catch(e){notice(e instanceof Error?e.message:"Could not update memory.")}};return <div className="page-grid"><section className="memory-toolbar span-3"><div><span className="eyebrow">SECOND BRAIN</span><h2>{data.length} durable memories</h2></div><div className="segmented"><button className={mode==="library"?"active":""} onClick={()=>setMode("library")}><Database size={15}/> Library</button><button className={mode==="map"?"active":""} onClick={()=>{setMode("map");void loadGraph(query)}}><Webhook size={15}/> Map</button></div></section>{mode==="library"?<Panel title="Memory library" eyebrow="VIEW · EDIT · DELETE · PRIVACY" className="span-3"><div className="memory-list">{data.map(m=><article className="memory-row" key={m.id}><i className={m.privacy||"personal"}/><div><header><span>{m.category}</span><small>{m.privacy||"personal"} · importance {m.importance}/5</small></header><p>{m.content}</p></div><div className="row-actions"><button onClick={()=>setEditing(m)}><Pencil size={15}/></button><button onClick={()=>remove(m)}><Trash2 size={15}/></button></div></article>)}</div></Panel>:<Panel title="Focused memory map" eyebrow="MAXIMUM 52 RELEVANT NODES" className="span-3"><form className="graph-search" onSubmit={e=>{e.preventDefault();void loadGraph(query)}}><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Focus on a person, project, course, or topic"/><button type="submit">Focus</button></form><Graph graph={graph}/></Panel>}{editing&&<MemoryEditor memory={editing} close={()=>setEditing(null)} save={save}/>}</div>}
function MemoryEditor({memory,close,save}:{memory:Memory;close:()=>void;save:(m:Memory)=>Promise<void>}){const [draft,setDraft]=useState(memory);return <div className="modal-backdrop"><form className="modal-panel" onSubmit={e=>{e.preventDefault();void save(draft)}}><header><div><span className="eyebrow">MEMORY CONTROL</span><h2>Edit memory</h2></div><button type="button" className="icon-button" onClick={close}><X size={18}/></button></header><label>Content<textarea value={draft.content} onChange={e=>setDraft({...draft,content:e.target.value})} rows={5}/></label><div className="form-grid"><label>Category<input value={draft.category} onChange={e=>setDraft({...draft,category:e.target.value})}/></label><label>Privacy<select value={draft.privacy||"personal"} onChange={e=>setDraft({...draft,privacy:e.target.value as Memory["privacy"]})}><option value="public">Public context</option><option value="personal">Personal</option><option value="sensitive">Sensitive</option><option value="restricted">Restricted — never inject</option></select></label><label>Importance<select value={draft.importance} onChange={e=>setDraft({...draft,importance:Number(e.target.value)})}>{[1,2,3,4,5].map(x=><option key={x}>{x}</option>)}</select></label><label className="check-label"><input type="checkbox" checked={Boolean(draft.locked)} onChange={e=>setDraft({...draft,locked:e.target.checked?1:0})}/> Lock from automatic edits</label></div><div className="modal-actions"><button type="button" className="quiet-button" onClick={close}>Cancel</button><button className="primary-button">Save changes</button></div></form></div>}
function Graph({graph}:{graph:{nodes:GraphNode[];edges:GraphEdge[]}}){const nodes=useMemo(()=>graph.nodes.map((n,i)=>{const a=i*2.399963,r=45+Math.sqrt(i)*35;return{...n,x:400+Math.cos(a)*r,y:265+Math.sin(a)*r}}),[graph.nodes]);const byId=new Map(nodes.map(n=>[Number(n.id),n]));return <div className="memory-graph"><svg viewBox="0 0 800 530"><defs><filter id="glow"><feGaussianBlur stdDeviation="3" result="b"/><feMerge><feMergeNode in="b"/><feMergeNode in="SourceGraphic"/></feMerge></filter></defs>{graph.edges.map(e=>{const s=byId.get(Number(e.source)),t=byId.get(Number(e.target));return s&&t?<line key={e.id} x1={s.x} y1={s.y} x2={t.x} y2={t.y} className="graph-edge"/>:null})}{nodes.map(n=><g key={n.id} transform={`translate(${n.x} ${n.y})`} className={`graph-node ${n.node_type}`}><circle r={8+n.importance*1.8} filter="url(#glow)"/><text y={22}>{n.label.slice(0,24)}</text></g>)}</svg>{!nodes.length&&<Empty icon={Brain} title="No focused memories" detail="Try another search."/>}</div>}

function Integrations({data,preview}:{data:SilkData;preview:boolean}){const cards:[typeof Home,string,string,boolean,(()=>void)?][]=[[CalendarDays,"Google Calendar","Read and manage events with Google OAuth",data.google.connected,()=>!preview&&location.assign("/api/google/connect")],[Search,"Tavily web search","Current web results with source links",Boolean(data.web.configured)],[Cloud,"OpenAI","Nano, Luna, and Terra with a server-side key",data.ai.primary_provider==="openai"],[Database,"Cloudflare D1","Private records and durable memory",!preview],[BookOpen,"Microsoft OneNote","Planned after Microsoft OAuth",false],[HeartPulse,"Apple Health","Requires a native iPhone companion",false]];return <div className="page-grid"><Panel title="Connections" eyebrow="TOOLS SILK CAN ACTUALLY USE" className="span-3"><div className="integration-grid">{cards.map(([Icon,name,detail,connected,action])=><article className="integration-card" key={name}><div className="connection-icon"><Icon/></div><div><h3>{name}</h3><p>{detail}</p></div><button className={connected?"connected-chip":"quiet-button"} onClick={action} disabled={connected||!action}>{connected?<><Check size={13}/> Connected</>:"Set up"}</button></article>)}</div></Panel></div>}
function SettingsView({data,preview,refresh,notice}:{data:SilkData;preview:boolean;refresh:()=>Promise<void>;notice:(s:string)=>void}){const [settings,setSettings]=useState(data.settings);const save=async()=>{if(preview)return notice("Preview settings are not persisted.");try{await api("/api/settings",{method:"PATCH",body:JSON.stringify(settings)});await refresh();notice("Settings saved.")}catch(e){notice(e instanceof Error?e.message:"Could not save settings.")}};const models=[["Router",data.ai.router_model||"gpt-5-nano","Tiny commands + memory extraction"],["Routine",data.ai.routine_model||"gpt-5.6-luna","Normal assistant work"],["Complex",data.ai.complex_model||"gpt-5.6-terra","Hard analysis only"]];return <div className="page-grid"><Panel title="Model routing" eyebrow="REAL SERVER CONFIGURATION" className="span-2"><div className="model-stack">{models.map(m=><article key={m[0]}><span>{m[0]}</span><strong>{m[1]}</strong><small>{m[2]}</small></article>)}</div><label className="field-label">Routing mode<select value={settings.model_mode} onChange={e=>setSettings({...settings,model_mode:e.target.value})}><option value="efficient">Efficient</option><option value="automatic">Automatic</option><option value="best">Best available</option></select></label><label className="field-label">Response length<select value={settings.response_length} onChange={e=>setSettings({...settings,response_length:e.target.value})}><option value="concise">Concise</option><option value="balanced">Balanced</option><option value="detailed">Detailed</option></select></label><button className="primary-button" onClick={save}>Save settings</button></Panel><Panel title="Usage & cost" eyebrow="THIS MONTH"><div className="hero-stat"><Gauge/><div><strong>{money(Number(data.usage.paid_cost_cad||0))}</strong><span>estimated paid OpenAI cost</span></div></div><div className="usage-lines"><span><small>Requests</small><strong>{Number(data.usage.requests||0)}</strong></span><span><small>USD guardrail</small><strong>${Number(data.ai.spend_limit_usd||data.usage.openai_spend_limit_usd||0).toFixed(2)}</strong></span><span><small>Remaining</small><strong>${Number(data.ai.remaining_usd||data.usage.openai_remaining_usd||0).toFixed(2)}</strong></span></div><Rule>Costs use recorded provider token usage.</Rule><Rule>Cloudflare neurons are reported separately.</Rule></Panel><Panel title="Security posture" eyebrow="OWNER-ONLY" className="span-3"><div className="security-grid"><Signal icon={LockKeyhole} label="API secrets" value="Server-side Worker variables"/><Signal icon={ShieldCheck} label="Session" value="Secure same-origin cookie"/><Signal icon={Database} label="Memory" value="Private D1 + privacy controls"/></div></Panel></div>}

function Core({activity,data}:{activity:{state:CoreState;label:string};data:SilkData}){return <div className="core-panel"><div className="core-heading"><span className="eyebrow">SILK CORE</span><span className="online-chip"><i/> ONLINE</span></div><div className={`core-orb ${activity.state}`}><div className="ring a"/><div className="ring b"/><div className="ring c"/><div className="core-center"><Mark small/></div><i className="orbit-dot one"/><i className="orbit-dot two"/></div><div className="core-activity"><span>{activity.state.toUpperCase()}</span><strong>{activity.label}</strong></div><div className="core-models"><CoreLine label="Router" value={short(data.ai.router_model)}/><CoreLine label="Routine" value={short(data.ai.routine_model)}/><CoreLine label="Complex" value={short(data.ai.complex_model)}/></div><div className="core-systems"><span><i className={data.google.connected?"ok":""}/>Calendar</span><span><i className={data.web.configured?"ok":""}/>Web</span><span><i className="ok"/>Memory</span></div><div className="core-note">Only factual tool activity is shown. Silk does not display hidden reasoning.</div></div>}
function CoreLine({label,value}:{label:string;value:string}){return <div><span>{label}</span><strong>{value}</strong></div>}
function minutes(v:number){const h=Math.floor(v/60),m=v%60;return h?`${h}h${m?` ${m}m`:""}`:`${m}m`}
function clock(v:number){return new Date(v*1000).toLocaleTimeString([],{hour:"numeric",minute:"2-digit"})}
function date(v:number){return new Date(v*1000).toLocaleDateString([],{month:"short",day:"numeric"})}
function relative(v:number){const m=Math.max(0,Math.round((Date.now()/1000-v)/60));return m<1?"just now":m<60?`${m}m ago`:`${Math.round(m/60)}h ago`}
function money(v:number){return new Intl.NumberFormat("en-CA",{style:"currency",currency:"CAD"}).format(v||0)}
function short(v?:string){return String(v||"Not set").replace("gpt-5.6-","").replace("gpt-5-","").toUpperCase()}
function previewGraph(memories:Memory[],query:string){const filtered=memories.filter(m=>!query||`${m.category} ${m.content}`.toLowerCase().includes(query.toLowerCase()));const nodes:GraphNode[]=[],edges:GraphEdge[]=[];const cats=new Map<string,number>();filtered.forEach(m=>{let id=cats.get(m.category);if(!id){id=10000+cats.size;cats.set(m.category,id);nodes.push({id,label:m.category,node_type:"category",privacy:"personal",importance:3})}nodes.push({id:m.id,label:m.content,node_type:"memory",privacy:m.privacy||"personal",importance:m.importance,memory_id:m.id});edges.push({id:m.id,source:m.id,target:id,relation:"category",weight:.8})});return{nodes,edges}}
